theme: jekyll-theme-minimal
title: [Yogesh Gajjar]
description: [A human with dreams of petting this cool cat! ]
logo: image1.jpeg
# permalink: https://jekyllrb.com/docs/configuration/front-matter-defaults/
# url: http://kolbytn.com/
# ---
# layout: post
# title: Blogging Like a Hacker
# ---

